name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write  # Required for OIDC for npm Trusted Publishing
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          package-manager-cache: false
          registry-url: https://registry.npmjs.org/
      - run: npm i --legacy-peer-deps
      - run: npm run run-all
      - run: npm publish
      - uses: dswistowski/surge-sh-action@v1
        with:
          domain: envisio-envy-ui.surge.sh
          project: './dist'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - run: |
          echo "current_version=$(echo $(npm view @envisio/envy-ui version))" >> "$GITHUB_ENV"
      - run: |
          curl -X POST \
          -H 'Content-type: application/json' \
          --data '{ "type": "mrkdwn", "text": "`${{ env.current_version }}` of `${{ github.repository }}` released" }' \
          ${{ secrets.SLACK_DEV_UI_CHANNEL_URL }}
